---
- name: Install requirements
  hosts: all
  remote_user: root
  become: yes
  gather_facts: yes
  vars:
    docker_apps:
      - docker-ce-18.09.9
      - docker-ce-cli-18.09.9
      - containerd.io
    # docker_apps_desired_state: absent
  roles:
    - robertdebock.bootstrap
    - robertdebock.core_dependencies
    - robertdebock.epel
    - robertdebock.python_pip
    - darkwizard242.docker
  tags: init

- name: Init master
  hosts: master
  remote_user: root
  become: yes
  gather_facts: yes
  roles:
    - role: robertdebock.java
      java_version: 8
    - role: gantsign.maven
  tags: master
