---
- robertdebock.bootstrap
- robertdebock.core_dependencies
- robertdebock.epel
- robertdebock.python_pip
# - robertdebock.docker_ce
# - geerlingguy.docker
- robertdebock.java
- gantsign.maven
- darkwizard242.docker
